---
name: 'Build Image'
on:
  schedule:
    - cron: '22 4 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: 'Lint'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci && npm run lint
  build:
    name: 'OCI'
    uses: curium-rocks/flows/.github/workflows/oci-build-image.yml@main
    needs:
      - lint
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write
    with:
      registry: ghcr.io/bryopsida
      image_name: openmct
